version: "3"
networks:
  app-network: null
services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: "nginx_techschool_backend"
    ports:
      - "81:80"
    volumes:
      - "./:/var/www/html"
      - "./nginx-default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql
    networks:
      - app-network
  mysql:
    image: "mariadb:10.5.8"
    container_name: "mysql_techschool_backend"
    restart: unless-stopped
    tty: true
    command: --max_allowed_packet=1073741824
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: techschool
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "php_techschool_backend"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - "./:/var/www/html"
      - "./php.ini:/usr/local/etc/php/php.ini"
    ports:
      - "9000:9000"
    networks:
      - app-network

  npm:
    image: "node:13.7"
    container_name: "npm_techschool_backend"
    volumes:
      - "./:/var/www/html"
    working_dir: /var/www/html
    entrypoint:
      - npm
